language: r
r:
- release
- devel
os:
- linux
- osx
matrix:
  exclude:
  - r: devel
    os: osx
sudo: false
cache: packages
warnings_are_errors: true
after_success:
    - Rscript -e 'covr::codecov(type="all")'